# -*- coding: utf-8 -*-
"""Projeto2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11WvPSyVwpJP8Knf3wz6DVKXEDdfUTHC9

Análise de dados com .csv

Desafio: Você trabalha em uma grande empresa de Cartão de Crédito e o diretor da empresa percebeu que o número de clientes que cancelam seus cartões tem aumentado significativamente, causando prejuízos enormes para a empresa

O que fazer para evitar isso? Como saber as pessoas que têm maior tendência a cancelar o cartão?

* Passo 1: Descobrir o porque os clientes estão cancelando os cartões, importando a base de Dados.
* Passo 2: Tratamento da base de Dados.
 - Excluir/Corrigir linhas e colunas vázias.
 - Ajeitar as colunas importadas.
 - Excluir colunas inúteis.
* Passo 3: Analisar a base de Dados.
 - Queremos descobrir os principais motivos de cancelamento de cartão.

Passo 1: Importar a base de dados.
"""

import pandas as pd

tabela_clientes = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ClientesBanco.csv',  encoding='latin1')
#encoding="latin1" quer dizer pro pandas que esse arquivo tm caracteres latinos, que não tem no ingles
tabela_clientes = tabela_clientes.drop('CLIENTNUM', axis=1)
#CLIENTNUM é o numero do cliente, é apagado (.drop, passa a variável e axis é o eixo, onde 0 é uma linha e 1 coluna) porque não nos ajuda em nada.
display(tabela_clientes)

"""Passo 2: Tratamento da base de Dados.
 - Já foi excluido coluna inútil no código acima.
 - Buscar por colunas com campos vazios.
 - Olhar como estão distribuidas as informações gerais.
"""

display(tabela_clientes.info()) #buscando nullos
tabela_clientes = tabela_clientes.dropna() #apagando as linhas que tem itens vazios
display(tabela_clientes.info())

#descrição do que está acontecendo, como o summary do R
display(tabela_clientes.describe())

"""Passo 3: analisar os dados.
- Olha como estão distribuidos os valores que queremos entender (Queremos descobrir os motivos dos clientes CANCELAREM os cartões).
- Analisar o 80/20 (regra de pareto) = olhar todas as caracteristicas dos clientes e descobrir os principais MOTIVOS de cancelamento.
"""

display(tabela_clientes["Categoria"].value_counts())
display(tabela_clientes["Categoria"].value_counts(normalize=True))
#normalize é mostrar a porcentagem de todos

import plotly.express as px  #pacote que cria grafico interativo
# para edições nos gráficos: https://plotly.com/python/histograms/

def grafico_coluna_categoria(coluna, tabela):
  fig = px.histogram(tabela, x=coluna, color='Categoria') # color_discrete_sequence=['#e6ad12', '#02b013']
  fig.show()

for coluna in tabela_clientes:
  grafico_coluna_categoria(coluna, tabela_clientes)

"""Antes o código era assim, funciona de boa e não sei qual a diferença:"""

for coluna in tabela_clientes:
   fig = px.histogram(tabela_clientes, x=coluna, color="Categoria")
   fig.show()

"""Anotação de conclusões analisadas através dos gráficos.

1. Na categória de Cartão, quase todos os clientes que cancelaram são do cartão Blue.
- Plano de ação --> analisar porque a categoria náo é vantajosa para o cliente. Como são so concorrentes da mesma categoria?
2. Na categória Contatos 12m, todos que precisaram ligar 6 vezes, cancelara. Quanto mais o cara precisar entrar em contato, mais chances para ele cancelar o cartão.
- Plano de ação --> analisar o motivo do contato/tratar os clientes que mais entraram em contato com o banco.
3. Na categória Limite Recebido, parece que quem não usa o limite do cartão ele cancela.
  - Percebe-se, na categoria Qtd de transações 12m, onde com mais de 60 transações, o cliente não cancela mais o cartão.
  - Clientes com menos de 60 transações são muito críticos.
  - A mesma coisa acontece com a Quantida de transações.
- Plano de ação --> Criar sistema de pontos, alguma bonificação apra incentivá-los a usar o cartão.

Confirmando tudo:

Podemos agora combinar as features dos nossos palpites para onde deve ser o nosso foco, seguindo a lógica 80-20

Qual a menor quantidade de problemas que conseguimos atacar que vão gerar o maior resultado?

Temos quase a totalidade dos Cancelados na bandeira "Blue", então já sabemos que nosso esforço deve ser focado ali

Mas vamos agora olhar mais a fundo:

Quantidade de Transações nos últimos 12m (ou valor das transações)
Quantidade de Contatos
"""

cancelados_df = tabela_clientes.loc[tabela_clientes['Categoria'] == 'Cancelado', :]

fig = px.histogram(cancelados_df, x='Qtde Transacoes 12m', nbins=5)
fig.show()

fig = px.histogram(cancelados_df, x="Valor Transacoes 12m", nbins=7)
fig.show()

criticos_df = tabela_clientes.loc[tabela_clientes['Qtde Transacoes 12m'] < 60, :]
fig = px.histogram(criticos_df, x='Contatos 12m')
fig.show()

qtde_ultra_criticos = len(criticos_df.loc[criticos_df['Contatos 12m'] > 2, :])

percentual_criticos = qtde_ultra_criticos / len(cancelados_df)
print(f'{percentual_criticos:.1%}')

"""Vamos ver como os Cancelados estão divididos ao todo:"""

for coluna in cancelados_df:
  grafico_coluna_categoria(coluna, cancelados_df)